import type { MediaKind } from "./types";

/**
 * Every path in the app, in one place. Each route is a function: called with a
 * value it builds the path to navigate to, and called with nothing it returns
 * the pattern React Router matches on, so a route is written once.
 */

/** The id a new manuscript sits under before it has been saved. */
export const NEW_MANUSCRIPT_ID = "new";

/** Which library a usage editor opens an asset from. */
export type UsageAsset = "background" | "sound";

/* Ids are generated by the app, but a restored backup can carry anything, so
   every value a path is built from is encoded. */
const segment = (value: string): string =>
  value.startsWith(":") ? value : encodeURIComponent(value);

const home = () => "/";

const dashboard = () => home();

const manuscripts = () => `${home()}manuscripts`;
const manuscript = (manuscriptId = ":manuscriptId") =>
  `${manuscripts()}/${segment(manuscriptId)}`;
const newManuscript = () => manuscript(NEW_MANUSCRIPT_ID);

const bible = () => `${home()}bible`;
const passages = () => `${home()}scripture`;
const passage = (passageId = ":passageId") =>
  `${passages()}/${segment(passageId)}`;

const images = () => `${home()}images`;
const image = (mediaId = ":mediaId") => `${images()}/${segment(mediaId)}`;
const videos = () => `${home()}videos`;
const video = (mediaId = ":mediaId") => `${videos()}/${segment(mediaId)}`;

const mediaLibrary = (kind: MediaKind) =>
  kind === "image" ? images() : videos();
const mediaItem = (kind: MediaKind, mediaId = ":mediaId") =>
  kind === "image" ? image(mediaId) : video(mediaId);

const sounds = () => `${home()}audio`;
const sound = (audioId = ":audioId") => `${sounds()}/${segment(audioId)}`;

const themes = () => `${home()}themes`;
const theme = (themeId = ":themeId") => `${themes()}/${segment(themeId)}`;

const stream = () => `${home()}stream`;

/** The editor that tunes one asset for a single slide, manuscript or passage. */
const assetUsages = () => `${home()}use`;
const assetUsage = (
  asset: UsageAsset | ":asset" = ":asset",
  assetId = ":assetId",
) => `${assetUsages()}/${asset}/${segment(assetId)}`;

/** The windows opened on a second screen, which render outside the app shell. */
const presentWindow = () => `${home()}present`;
const streamWindow = () => `${home()}stream-live`;

/** Anything unmatched falls back to the dashboard. */
const notFound = () => "*";

const routes = {
  home,
  dashboard,
  manuscripts,
  manuscript,
  newManuscript,
  bible,
  passages,
  passage,
  images,
  image,
  videos,
  video,
  mediaLibrary,
  mediaItem,
  sounds,
  sound,
  themes,
  theme,
  stream,
  assetUsage,
  presentWindow,
  streamWindow,
  notFound,
};

export default routes;

export const isRoutePath = (candidate: string): boolean =>
  candidate.startsWith("/");

/**
 * Whether a navigation destination is the page being shown. The dashboard is
 * matched exactly because every other path starts with it.
 */
export const isRouteActive = (route: string, pathname: string): boolean =>
  route === dashboard()
    ? pathname === route
    : pathname === route || pathname.startsWith(`${route}/`);

/** Pages that scroll their own panels rather than letting the app shell scroll. */
const SELF_SCROLLING_PAGES = [bible(), themes()];

/** Sections whose editor does the same, but whose library page does not. */
const SELF_SCROLLING_EDITORS = [
  passages(),
  manuscripts(),
  images(),
  videos(),
  sounds(),
  assetUsages(),
];

export const isSelfScrollingRoute = (pathname: string): boolean =>
  SELF_SCROLLING_PAGES.some((route) => isRouteActive(route, pathname)) ||
  SELF_SCROLLING_EDITORS.some((route) => pathname.startsWith(`${route}/`));
